---
debug: false
redis:
  expirationS: 20
  operationTimeoutMs: 100
test:
  minClients: 1
  maxClients: 2000
  stageIntervalMs: 1000
  requestDelayMs: 1000
  keySize: 8
  valueSize: 10
  workload: set_get
  batchSize: 10
  sameSlotPerClient: false
controller:
  httpTimeoutMs: 10000
