{
 "title": "RedBench",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "command",
    "query": {
     "query": "label_values(redbench_request_duration_seconds_count,op)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(redbench_request_duration_seconds_count,job)"
    }
   },
   { "name": "p", "query": "0.5,0.75,0.90,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "latency $command p$p",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "command",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($p, sum by(command, le,job) (\n  rate(redbench_request_duration_seconds_bucket{command=~\"$command\"}[$__rate_interval]))\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (command,job) (rate(redbench_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{job}} -> {{command}}"
    }
   ]
  },
  {
   "title": "client count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redbench_stage{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "repeat": "job",
     "targets": [
      {
       "expr": "sum by(le) (rate(redbench_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval]) )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}