{
 "title": "RedBench",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "command",
    "query": {
     "query": "label_values(redbench_request_duration_seconds_count,command)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(redbench_request_duration_seconds_count,target)"
    }
   },
   { "name": "p", "query": "0.5,0.75,0.90,0.95,0.99,0.999" }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "latency $command p$p",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "command",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($p, sum by(command, le,target) (\n  rate(redbench_request_duration_seconds_bucket{command=~\"$command\"}[$__rate_interval]))\n)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (command,target) (rate(redbench_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{target}} -> {{command}}"
    }
   ]
  },
  {
   "title": "Failed RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (command,target) (rate(redbench_request_failed_total{command=~\"$command\", target=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target}} -> {{command}}"
    }
   ]
  },
  {
   "title": "client count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redbench_stage{target=~\"$target\"}",
     "legendFormat": "{{job}} - {{target}}"
    }
   ]
  },
  {
   "title": "Redis connection pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "timeseries",
     "description": "Active + idle",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "redbench_redis_pool_total_conns{target=~\"$target\"}",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Hit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(redbench_redis_pool_hits{target=~\"$target\"}[$__rate_interval])",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Miss rate",
     "type": "timeseries",
     "description": "Active + idle",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(redbench_redis_pool_misses{target=~\"$target\"}[$__rate_interval])",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Stale/timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "redbench_redis_pool_stale_conns{target=~\"$target\"} > 0",
       "legendFormat": "stale conns {{target}}"
      },
      {
       "expr": "rate(redbench_redis_pool_timeouts{target=~\"$target\"}[$__rate_interval])",
       "legendFormat": "timeouts {{target}}"
      }
     ]
    }
   ]
  },
  {
   "title": "heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "$target",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 126 },
     "repeat": "target",
     "targets": [
      {
       "expr": "sum by(le) (rate(redbench_request_duration_seconds_bucket{target=~\"$target\"}[$__rate_interval]) )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}