package config

import (
	"fmt"
	"net/url"
	"os"
	"reflect"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v2"
)

// Workload identifiers kept in one place to avoid magic strings.
const (
	WorkloadSetGet    = "set_get"
	WorkloadMSetMGet  = "mset_mget"
	WorkloadHSetHMGet = "hset_hmget"
	WorkloadZSet      = "zset_leaderboards"
	// DefaultConnectTimeoutSeconds is the fallback Redis connection timeout used
	// when none is explicitly provided by the caller.
	DefaultConnectTimeoutSeconds = 5
)

// IsBatchWorkload reports whether the given workload uses batch operations.
// Keeping this here allows future batch workloads to be added without touching call sites.
func IsBatchWorkload(workload string) bool {
	switch workload {
	case WorkloadMSetMGet, WorkloadHSetHMGet, WorkloadZSet:
		return true
	default:
		return false
	}
}

// Config represents the application configuration.
type Config struct {
	Debug      bool             `yaml:"debug" json:"debug"`
	Redis      RedisConfig      `yaml:"redis" json:"redis"`
	Test       Test             `yaml:"test" json:"test"`
	Controller ControllerConfig `yaml:"controller" json:"controller"`
}

// RedisConfig contains Redis-specific configuration.
type RedisConfig struct {
	Expiration         int32 `yaml:"expirationS" json:"expiration"`
	OperationTimeoutMs int   `yaml:"operationTimeoutMs" json:"operationTimeoutMs"`
}

// Test contains benchmark test configuration.
type Test struct {
	MinClients      int `yaml:"minClients" json:"minClients"`
	MaxClients      int `yaml:"maxClients" json:"maxClients"`
	StageIntervalMs int `yaml:"stageIntervalMs" json:"stageIntervalMs"`
	RequestDelayMs  int `yaml:"requestDelayMs" json:"requestDelayMs"`
	KeySize         int `yaml:"keySize" json:"keySize"`
	ValueSize       int `yaml:"valueSize" json:"valueSize"`
	// Workload selects the workload flavor: "set_get" (default), "mset_mget", "hset_hmget" or "zset_leaderboards"
	Workload string `yaml:"workload" json:"workload"`
	// BatchSize is used for batch workloads (e.g., MSET/MGET)
	BatchSize int `yaml:"batchSize" json:"batchSize,omitempty"`
	// SameSlotPerClient, when true, uses a consistent Redis Cluster hash slot tag for all keys generated by a single logical client operation/batch
	SameSlotPerClient bool `yaml:"sameSlotPerClient" json:"sameSlotPerClient,omitempty"`
	// TagsCount controls the number of distinct cluster hash-slot tags to spread keys across for cluster-aware workloads (e.g., ZSET leaderboards).
	TagsCount int `yaml:"tagsCount" json:"tagsCount,omitempty"`
	// ZSET-specific knobs
	// ZSetBatchSize controls number of members per ZADD batch for ZSET workload.
	ZSetBatchSize int `yaml:"zsetBatchSize" json:"zsetBatchSize,omitempty"`
	// ZSetTopK controls how many members are read and retained per leaderboard (trim keeps topK).
	ZSetTopK int `yaml:"zsetTopK" json:"zsetTopK,omitempty"`
	// ZSetPerTagLeaderboards controls how many leaderboard keys exist per tag (union fan-in is bounded by this).
	ZSetPerTagLeaderboards int `yaml:"zsetPerTagLeaderboards" json:"zsetPerTagLeaderboards,omitempty"`
	// ZSetUnionFanIn controls how many leaderboards to union per union operation (0 disables unions).
	ZSetUnionFanIn int `yaml:"zsetUnionFanIn" json:"zsetUnionFanIn,omitempty"`
	// Advanced knobs (optional)
	// ZSetUnionEveryNOps controls union frequency. For example 8 means ~every 1/8 ops.
	ZSetUnionEveryNOps int `yaml:"zsetUnionEveryNOps" json:"zsetUnionEveryNOps,omitempty"`
	// ZSetUpdateRatio is 0..100. If >0, a portion of operations do ZINCRBY on existing members.
	ZSetUpdateRatio int `yaml:"zsetUpdateRatio" json:"zsetUpdateRatio,omitempty"`
	// ZSetScoreMode controls how scores are generated: "time", "random", "increment".
	ZSetScoreMode string `yaml:"zsetScoreMode" json:"zsetScoreMode,omitempty"`
}

// ControllerConfig contains controller-specific configuration.
type ControllerConfig struct {
	HTTPTimeoutMs int `yaml:"httpTimeoutMs" json:"httpTimeoutMs"` // HTTP timeout for worker communication in milliseconds
}

// HTTPTimeout returns the HTTP timeout as a time.Duration.
func (c ControllerConfig) HTTPTimeout() time.Duration {
	return time.Duration(c.HTTPTimeoutMs) * time.Millisecond
}

// RedisConnection holds Redis connection information.
type RedisConnection struct {
	ClusterURL            string `json:"clusterURL,omitempty"`
	TargetLabel           string `json:"targetLabel,omitempty"`
	URL                   string `json:"url,omitempty"`                   // Redis URL (redis://)
	ConnectTimeoutSeconds int    `json:"connectTimeoutSeconds,omitempty"` // Connection timeout in seconds
}

// SetTargetLabel sets the target label for metrics based on the connection configuration.
func (conn *RedisConnection) SetTargetLabel() {
	if conn.ClusterURL != "" {
		conn.TargetLabel = conn.ClusterURL
	} else if conn.URL != "" {
		conn.TargetLabel = conn.URL
	} else {
		conn.TargetLabel = "unspecified"
	}
}

// ParseURL parses a Redis URL and populates connection fields.
// Supports redis:// scheme only.
func (conn *RedisConnection) ParseURL() error {
	if conn.URL == "" {
		return nil
	}

	u, err := url.Parse(conn.URL)
	if err != nil {
		return fmt.Errorf("invalid URL format: %w", err)
	}

	// Only support redis scheme
	if u.Scheme != "redis" {
		return fmt.Errorf("unsupported scheme: %s (use redis://)", u.Scheme)
	}

	return nil
}

// ParseClusterURL parses a Redis cluster URL and populates connection fields.
// Supports both full URLs (redis://host:port) and plain host:port format.
func (conn *RedisConnection) ParseClusterURL() error {
	if conn.ClusterURL == "" {
		return nil
	}

	clusterURL := conn.ClusterURL

	// Check if it's a full URL or just host:port
	if strings.Contains(clusterURL, "://") {
		// Full URL format
		u, err := url.Parse(clusterURL)
		if err != nil {
			return fmt.Errorf("invalid cluster URL format: %w", err)
		}
		if u.Scheme != "redis" {
			return fmt.Errorf("unsupported cluster URL scheme: %s (use redis://)", u.Scheme)
		}

		// Extract host:port
		hostPort := u.Host
		if u.Port() == "" {
			// Add default port if not specified
			hostPort = u.Hostname() + ":6379"
		}

		// Update ClusterURL to be just the host:port (go-redis expects this format)
		conn.ClusterURL = hostPort
	} else {
		// Plain host:port format (backward compatibility)
		// Add default port if not specified
		if !strings.Contains(clusterURL, ":") {
			conn.ClusterURL = clusterURL + ":6379"
		}
	}
	return nil
}

// LoadConfig loads configuration from the specified YAML file.
// It returns the loaded configuration or an error if loading fails.
func LoadConfig(path string) (*Config, error) {
	cfg := new(Config)

	f, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config file: %w", err)
	}

	err = yaml.Unmarshal(f, cfg)
	if err != nil {
		return nil, fmt.Errorf("parsing config file: %w", err)
	}

	// Override Test fields from ENV variables
	testVal := reflect.ValueOf(&cfg.Test).Elem()
	testType := testVal.Type()
	for i := 0; i < testVal.NumField(); i++ {
		field := testType.Field(i)
		fieldName := field.Name
		// ENV var: TEST_<UPPERCASE_FIELDNAME>
		envName := "TEST_" + toEnvName(fieldName)
		if val, ok := os.LookupEnv(envName); ok {
			switch testVal.Field(i).Kind() {
			case reflect.Int, reflect.Int32, reflect.Int64:
				if intVal, err := strconv.Atoi(val); err == nil {
					testVal.Field(i).SetInt(int64(intVal))
				}
			case reflect.Bool:
				if parsed, err := strconv.ParseBool(val); err == nil {
					testVal.Field(i).SetBool(parsed)
				}
			case reflect.String:
				testVal.Field(i).SetString(val)
			}
		}
	}

	// Load Controller configuration with defaults and environment overrides
	cfg.Controller = LoadControllerConfig()

	return cfg, nil
}

// LoadRedisConnection loads Redis connection configuration from environment variables.
// It supports both traditional host/port configuration and redis:// URLs.

// NewRedisConnection creates a new RedisConnection with the given timeout.
func NewRedisConnection(timeoutSeconds int) *RedisConnection {
	return &RedisConnection{
		ConnectTimeoutSeconds: timeoutSeconds,
	}
}

// ApplyDefaults ensures all required fields have default values.
func (conn *RedisConnection) ApplyDefaults() {
	conn.SetTargetLabel()
}

// getBoolEnv gets a boolean environment variable with a default value.
func getBoolEnv(key string, defaultValue bool) bool {
	if val := os.Getenv(key); val != "" {
		if parsed, err := strconv.ParseBool(val); err == nil {
			return parsed
		}
	}
	return defaultValue
}

// getIntEnv gets an integer environment variable with a default value.
func getIntEnv(key string, defaultValue int) int {
	if val := os.Getenv(key); val != "" {
		if parsed, err := strconv.Atoi(val); err == nil {
			return parsed
		}
	}
	return defaultValue
}

// LoadControllerConfig loads controller configuration from environment variables with defaults.
func LoadControllerConfig() ControllerConfig {
	return ControllerConfig{
		HTTPTimeoutMs: getIntEnv("CONTROLLER_HTTP_TIMEOUT_MS", 10000), // Default 10 seconds
	}
}

// toEnvName converts CamelCase to upper snake case (e.g., MinClients -> MINCLIENTS)
func toEnvName(s string) string {
	res := ""
	for i, c := range s {
		if i > 0 && c >= 'A' && c <= 'Z' {
			res += "_"
		}
		res += string(c)
	}
	return strings.ToUpper(res)
}
